# Generated by Django 5.2.11 on 2026-03-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='ultima_interacao_em',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
